### PR TITLE
feat(docgen): new generator for TypeScript declaration

### PR DESCRIPTION
**Pull request by drauggres**
Output for current [master](https://github.com/appcelerator/titanium_mobile/commit/b295e6321ba38e29612b51d93c1518e87e6fffee) (9.0.0) branch: [titanium.d.ts](https://gist.github.com/drauggres/77a0bd495ca3e7d4a7dbd7e170156fb6)

Pros:

1.  Dictionary<T> (typed factory methods):
 ```typescript
 const button = Ti.UI.createButton({
  width: 100,
  backgroundColor: '#ddd',
  text: '+',   // TS2345: [..] 'text' does not exist in type [..]
  left: 10
});
```
2. Types for "addEventListner", "removeEventListener":
 ```typescript
const button = Ti.UI.createButton();
button.addEventListener('click', function(e) {
  this.backgroundColor = 'red';
  this.text = 123;  // TS2339: Property 'text' does not exist on type 'Button'.
});
``` 
3. Types for Events:
 ```typescript
const button = Ti.UI.createButton();

// know event type
button.addEventListener('click', function(e) {
  e.source.backgroundColor = 'red';
  console.log(`x: ${e.x}`);
  console.log(`x: ${e.z}`);  // TS2339: Property 'z' does not exist on type 'Button_click_Event'.
});

// unknown event type
button.addEventListener('myEvent', function(e) {
  console.log(e.lol);  // ok, because 'myEvent' is unknown event type -> e: any
});

``` 

4.  Modules declared as both `namespace` and `class` (with static methods). This allows to define types for specific events for Modules like `Ti.Geolocation`, `Ti.Media`, `Ti.Network` etc.:
```typescript
Ti.Network.addEventListener('change', e => {
  console.log(e.reason);
  console.log(e.status);  // TS2339: Property 'status' does not exist on type 'Network_change_Event'
});
```

Cons:
1. Any custom properties are not allowed (~~even `id`~~ `Ti.UI.View` [now](https://github.com/appcelerator/titanium_mobile/pull/11353) have `id` property):
```typescript
Ti.UI.createView({
  id: 'myViewId',
  myProp: 'content'  // TS2345: [..] 'myProp' does not exist in type [..]
});
```

### CODE REVIEW

**Comment by drauggres** [comment]
I know, that you already have `.d.ts` generator, so it's ok if this PR is not going to be merged.
But I would really like to see these features in `@types/titanium`

Also generated file revealed some mistakes in the documentation (you can find them by `#Error` comment in it) , so I will refer to this PR in the upcoming TIDOC tickets.

**Comment by janvennemann** [comment]
So from a first quick look I really like these changes and would love to get them in for our existing TypeScript generator. The cons are negligible i guess. If you absolutely need custom properties you can still cast the created proxy to `any` and assign whatever you want.

@drauggres do you think you can easily adopt these new features to our existing TypeScript generator?

**Comment by drauggres** [comment]
> The cons are negligible i guess.

I have an idea of changing Alloy in a way that it will generate TS classes, and everything (including code generated from xml-views, tss-styles, models and collections) could be checked for types.

Problem is that `id` is really fundamental property (and somehow it is not in the API). Strict types checking will not allow it and casting to `any` nullifies the point of typing.

>@drauggres do you think you can easily adopt these new features to our existing TypeScript generator?
I just found some flaws in my generator (that's why I changed title to `WIP`), so I will need more time to process the SDK API structure before even thinking about it (don't think it will be easy).

**Comment by drauggres** [comment]
OK. Now I'm satisfied with the generated result. This is how I would like to see `@types/titanium`.

> do you think you can easily adopt these new features to our existing TypeScript generator?
I will look into it and if I succeed than I'll open a new PR.

**Comment by drauggres** [comment]
@janvennemann Sorry for disturbing you, but do you know where documentation for Windows platform is coming from?
I don't see it in the SDK and therefore in the generated `d.ts`.

**Comment by drauggres** [comment]
closed in favor of https://github.com/appcelerator/docs-devkit/pull/25

**Pull request closed without merging**
